// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhlO0w7ea4Hhe5a_QtALDjWOXGoyHym-Y',
    appId: '1:173668907815:web:bd13a17bef1f494b070702',
    messagingSenderId: '173668907815',
    projectId: 'budgetb-1daf6',
    authDomain: 'budgetb-1daf6.firebaseapp.com',
    storageBucket: 'budgetb-1daf6.firebasestorage.app',
    measurementId: 'G-TJ044KQ12B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3f7AE0aEn7R85Ug84U1tCmwsdmZeGb6Q',
    appId: '1:173668907815:android:369f189a40fdc9c0070702',
    messagingSenderId: '173668907815',
    projectId: 'budgetb-1daf6',
    storageBucket: 'budgetb-1daf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHwwz3leyeSK9OdN6ecq8T3HY8Hc__S8',
    appId: '1:173668907815:ios:661ff8ebb1218d43070702',
    messagingSenderId: '173668907815',
    projectId: 'budgetb-1daf6',
    storageBucket: 'budgetb-1daf6.firebasestorage.app',
    iosBundleId: 'com.example.budgetb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPHwwz3leyeSK9OdN6ecq8T3HY8Hc__S8',
    appId: '1:173668907815:ios:661ff8ebb1218d43070702',
    messagingSenderId: '173668907815',
    projectId: 'budgetb-1daf6',
    storageBucket: 'budgetb-1daf6.firebasestorage.app',
    iosBundleId: 'com.example.budgetb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhlO0w7ea4Hhe5a_QtALDjWOXGoyHym-Y',
    appId: '1:173668907815:web:ec65e19e5bfcc585070702',
    messagingSenderId: '173668907815',
    projectId: 'budgetb-1daf6',
    authDomain: 'budgetb-1daf6.firebaseapp.com',
    storageBucket: 'budgetb-1daf6.firebasestorage.app',
    measurementId: 'G-NWEBFBP4D0',
  );
}
